engines:
  checkstyle:
    enabled: true
    channel: "beta"    
    checks:
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false
  pmd:
    enabled: true
    channel: "beta"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.java"